spring:
    application:
        name: AskHR
    ai:
        mistralai:
            api-key: ${MISTRAL_AI_API_KEY}
        vectorstore:
            pgvector:
            index-type: HNSW
            distance-type: COSINE_DISTANCE
            dimensions: 1536
            max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
            enabled: true
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: ${PG_VECTOR_DB_USERNAME}
        password: ${PG_VECTOR_DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    
file:
    upload:
        path: ${FILE_PATH}
server:
    port: 8080